### ISSUE TITLE
"Bad Request - Action: " with GoLang github.com/aws/aws-sdk-go-v2/service/sqs v1.28.0

### ISSUE THREAD

**Issue by keithMqG** [Admiral-Piett/goaws#281] opened 2023-11-15 07:46 UTC
Attempting to use GetQueueUrl with GoLang  _**github.com/aws/aws-sdk-go-v2/service/sqs v1.28.0**_ causes Bad Request.

Works fine with v1.24.7.

Needs further investigation.

**Comment by gitaugakwa** [comment] 2023-11-22 21:00
Getting the same with a local build from 42f5c2de159de2ffc8b69ed42908d2acbd529a83 commit.

Using both the postman collection and the was cli

**Comment by gitaugakwa** [comment] 2023-11-22 21:09
My bad, I wasn't sending the appropriate body using the collection.

Works with the postman but the cli doesn't work with a command like
`aws --endpoint-url http://localhost:4100 --profile Profile --region eu-west-1 sqs list-queues`

**Comment by jrhy** [comment] 2023-11-28 22:59
I see a similar response after upgrading from github.com/aws/aws-sdk-go from v1.45.28 to v1.48.6. It could be because the SDK request format has changed, and no longer uses `Content-Type: application/x-www-form-urlencoded`, but `Content-Type: application/x-amz-json-1.0`, like:

```
POST / HTTP/1.1
Host: 127.0.0.1:9324
Accept-Encoding: zstd,gzip
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20231128T222049Z
X-Amz-Target: AmazonSQS.GetQueueUrl

{"QueueName":"dev-coi-request"}
```

**Comment by jrhy** [comment] 2023-11-28 23:28
The AWS SDK v2 began supporting JSON requests in v1.28.0, and the AWS SDK v1 in v1.47.7, according to https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-json-faqs.html .

**Comment by iamed2** [comment] 2024-01-25 16:00
AWS changed the service definition in-place for SQS without a version change, switching it from Query to JSON. Most SDKs will not be set up to handle both versions; either they are custom-written (rare) and will continue using the Query protocol, or they are auto-generated and will switch to the JSON protocol when regenerated from recent specs. I haven't yet seen an SDK that supports the JSON protocol for SQS but allows forcing the Query protocol.

Likely there is a significant portion of users in both camps right now.

**Comment by Admiral-Piett** [comment] 2024-01-26 16:06
I think this is a duplicate of https://github.com/Admiral-Piett/goaws/issues/279 we are working on implementing JSON processing as quickly as we can.  Though the work is significant, and I only have so much time.  🙂

There's a feature branch in that issue with the work in progress if anyone would like to track and/or contribute.

Closing as a duplicate.

**Closed by Admiral-Piett** 2024-01-26 16:06 UTC
